[package]
name = "slsengine"
version = "0.1.0"
authors = ["Steve Shea <stevenlsjr@gmail.com>"]

[features]
#with-vulkan = ["ash"]

[dependencies]
gl = "0.10.0"
cgmath = "0.16.1"
failure = "0.1.2"
serde = "1.0.79"
serde_derive = "1.0.79"
memoffset = "0.2.1"
genmesh = "0.6.2"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2.git"

[dependencies.ash]
optional = false
version = "0.24.0"

[target.wasm32-unknown-emscripten.dependencies]
stdweb = "0.4.9"
webgl_stdweb = "0.2.0"

