[package]
name = "slsengine"
version = "0.1.0"
authors = ["Steve Shea <stevenlsjr@gmail.com>"]

[features]
default=["with-vulkan", "gl-debug-output"]
with-vulkan = ["ash", "vulkano", "vulkano-shaders"]
gl-debug-output = []

[dependencies]
bitflags = "1.0.4"
cgmath = {version="0.16.1", features=["swizzle"]}
failure = "0.1.3"
genmesh = "0.6.2"
gl = {path ="lib/gl"}
image = "0.20.1"
memoffset = "0.2.1"
rand = { version = "0.5.5", default-features = false }
serde = "1.0.79"
serde_derive = "1.0.80"
stb_image = "0.2.2"
vulkano = {version= "0.11.1", optional= true}
vulkano-shaders = {version= "0.11.0", optional= true}
toml = "0.4.9"

[dependencies.gltf]
version = "0.11"
features = ["extras", "names"]

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2.git"

[dependencies.ash]
optional = true
version = "0.24.0"


