[package]
name = "slsengine"
version = "0.1.0"
authors = ["Steve Shea <stevenlsjr@gmail.com>"]

[dependencies]
gl = "0.10.0"
cgmath = "0.16.1"
sdl2 = "0.31.0"

[target.wasm32-unknown-emscripten.dependencies]
stdweb = "0.4.9"
