[package]
name = "slsengine"
version = "0.1.0"
authors = ["Steve Shea <stevenlsjr@gmail.com>"]

[features]
default=["with-vulkan"]
with-vulkan = ["ash", "vulkano", "vulkano-shaders"]
gl-debug-output = []

[dependencies]
gl = {path ="lib/gl"}
cgmath = "0.16.1"
failure = "0.1.2"
serde = "1.0.79"
serde_derive = "1.0.79"
memoffset = "0.2.1"
genmesh = "0.6.2"
image = "0.20.0"
stb_image = "0.2.2"
vulkano = {version= "0.11.0", optional= true}
vulkano-shaders = {version= "0.11.0", optional= true}

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2.git"

[dependencies.ash]
optional = true
version = "0.24.0"

[target.wasm32-unknown-emscripten.dependencies]
stdweb = "0.4.9"
webgl = {path= "lib/webgl"}

