[package]
name = "slsengine-rs"
version = "0.1.0"
authors = ["Steve Shea <stevenlsjr@gmail.com>"]

[dependencies]
gl = "0.10.0"
cgmath = "0.16.1"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.9"
