# The default value of `--target` used when building this crate
# in cases where it's not specified on the command line.
default-target = "wasm32-unknown-emscripten"

# This will prepend a given JavaScript file to the resulting `.js` artifact.
# You can put any initialization code here which you'd like to have executed
# when your `.js` file first loads.
#
# This accepts either a string (as shown here), or an array of strings,
# in which case it will prepend all of the specified files in their
# order of appearance.
# prepend-js = "./assets/prelude.js"

[cargo-web]
minimum-version = "0.6.0"

# These will only take effect on *-emscripten targets.
[target.emscripten]
link-args = ["-s", "USE_SDL=2", "-s", "FULL_ES2=1"]