[package]
name = "slsengine-platform-sdl"
version = "0.1.0"
authors = ["Steve Shea <stevenlsjr@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"

serde = "1.0.90"
serde_derive = "1.0.90"
log = "0.4"


[dependencies.sdl2]
  version="0.32.2"