[package]
name = "vulkan"
version = "0.1.0"
authors = ["Steve Shea <stevenlsjr@gmail.com>"]
edition = "2018"

[dependencies]
slsengine-backend-vk = {path="../../slsengine-backend-vk"}
failure = "0.1.5"
log = "0.4"
